<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>outlet selection radio button</name>
   <tag></tag>
   <elementGuidId>bffacf33-6174-422d-b36a-4fca537ae736</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mCSB_1_container&quot;]/li[2]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;mCSB_1_container&quot;]/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sprite-liSel-1 sprite_new mradioicon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mCSB_1_container&quot;]/li[2]</value>
   </webElementProperties>
</WebElementEntity>
