<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Create New Product new prod</name>
   <tag></tag>
   <elementGuidId>5365b276-30a5-45ba-801d-e32cbbcd3b7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;webPorductSearchContainer0&quot;]/div/div[2]/div/li</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[@class = 'fixed-footer create-product-div ng-scope ng-binding jd-li-hover']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>showCreateProduct</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fixed-footer create-product-div ng-scope ng-binding jd-li-hover</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-hide</name>
      <type>Main</type>
      <value>hideCreateProduct</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>createProduct()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					Create New Product &quot;new products&quot;
				</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;webPorductSearchContainer0&quot;)/div[@class=&quot;input-group jd-autosuggest-holder jd-open search-barcode hide-search-option&quot;]/div[@class=&quot;input-group dynamic-height-div&quot;]/div[@class=&quot;search-result-container jd-autosuggest-fixed-footer&quot;]/li[@class=&quot;fixed-footer create-product-div ng-scope ng-binding jd-li-hover&quot;]</value>
   </webElementProperties>
</WebElementEntity>
