<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>purchase qty</name>
   <tag></tag>
   <elementGuidId>8e39f849-cba3-4e34-8cac-5f2a1dbfe895</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;content&quot;]/div/div[1]/div[2]/div[2]/div[2]/form/fieldset/div/div[3]/div/div[2]/div[2]/div[3]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;content&quot;)/div[@class=&quot;clearfix ng-scope&quot;]/div[@class=&quot;web-left-container web-purchase-order-manage ng-scope&quot;]/div[@class=&quot;web-left-body&quot;]/div[@class=&quot;web-left-body-section clearfix&quot;]/div[@class=&quot;col-right&quot;]/form[@class=&quot;ng-valid ng-dirty&quot;]/fieldset[1]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;form-group col-sm-12&quot;]/div[@class=&quot;margin0&quot;]/div[@class=&quot;jd-div-border jd-overflow-auto po-table&quot;]/div[@class=&quot;clearfix width100perc row margin0 ng-scope&quot;]/div[@class=&quot;text-right jd-padding-left-0 col-md-3 display-inline-block  jd-web-validation-error&quot;]/input[@class=&quot;form-control width100px text-right display-inline-block enteredQuantity ng-valid ng-dirty&quot;][count(. | //input[@type = 'text']) = count(//input[@type = 'text'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>product.enteredQuantity</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jd-set-focus</name>
      <type>Main</type>
      <value>setFocusOnQuantity</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control width100px text-right display-inline-block enteredQuantity ng-valid ng-dirty</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>checkQty($index)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>!isInvoicePage</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keydown</name>
      <type>Main</type>
      <value>setFocusOnSearch($event)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow-decimal</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;clearfix ng-scope&quot;]/div[@class=&quot;web-left-container web-purchase-order-manage ng-scope&quot;]/div[@class=&quot;web-left-body&quot;]/div[@class=&quot;web-left-body-section clearfix&quot;]/div[@class=&quot;col-right&quot;]/form[@class=&quot;ng-valid ng-dirty&quot;]/fieldset[1]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;form-group col-sm-12&quot;]/div[@class=&quot;margin0&quot;]/div[@class=&quot;jd-div-border jd-overflow-auto po-table&quot;]/div[@class=&quot;clearfix width100perc row margin0 ng-scope&quot;]/div[@class=&quot;text-right jd-padding-left-0 col-md-3 display-inline-block  jd-web-validation-error&quot;]/input[@class=&quot;form-control width100px text-right display-inline-block enteredQuantity ng-valid ng-dirty&quot;]</value>
   </webElementProperties>
</WebElementEntity>
